input_channel_names:
- GFP
time_indices: all
reconstruction_dimension: 3
fluorescence:
  transfer_function:
    yx_pixel_size: 0.325
    z_pixel_size: 2.0
    z_padding: 0
    z_focus_offset: 0
    index_of_refraction_media: 1.3
    numerical_aperture_detection: 1.2
    wavelength_emission: 0.507
  apply_inverse:
    reconstruction_algorithm: Tikhonov
    regularization_strength: 0.001
    TV_rho_strength: 0.001
    TV_iterations: 1
