input_channel_names:
- BF
time_indices: all
reconstruction_dimension: 3
phase:
  transfer_function:
    wavelength_illumination: 0.532
    yx_pixel_size: 0.325
    z_pixel_size: 2.0
    z_padding: 0
    z_focus_offset: 0
    index_of_refraction_media: 1.3
    numerical_aperture_detection: 1.2
    numerical_aperture_illumination: 0.5
    invert_phase_contrast: false
  apply_inverse:
    reconstruction_algorithm: Tikhonov
    regularization_strength: 0.001
    TV_rho_strength: 0.001
    TV_iterations: 1
